package constant

const (
	// TASK_STATUS_PENDING 任务状态：待处理
	TASK_STATUS_PENDING = 1
	// TASK_STATUS_PROCESSING 任务状态：处理中
	TASK_STATUS_PROCESSING = 2
	// TASK_STATUS_SUCC 任务状态：成功
	TASK_STATUS_SUCC = 3
	// TASK_STATUS_FAILED 任务状态：失败
	TASK_STATUS_FAILED = 4
)
